source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ASCIIfy_Example' do
  pod 'ASCIIfy', :path => '../'

  target 'ASCIIfy_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
