language: objective-c
osx_image: xcode7.3

cache: cocoapods
podfile: Example/Podfile

email:
  on_failure: change

script:
- set -o pipefail && xcodebuild test -workspace Example/ASCIIfy.xcworkspace -scheme ASCIIfy_iOS_Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
